version: '3'

services:
  web:
    image: gcr.io/mizizi/beulahcity_com_web/staging:latest
    ports:
      - '15005:8000'
    env_file:
      - .env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
