# Generated by Django 2.2.7 on 2019-11-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_details_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='project_information',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='project_information_title',
            field=models.TextField(blank=True),
        ),
    ]
