# Generated by Django 2.2.7 on 2019-11-22 15:30

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_projectpage_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='hero_intro',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='project_body',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='project_intro',
            field=models.TextField(blank=True),
        ),
    ]
