# Generated by Django 2.2.7 on 2019-11-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20191122_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='project_url',
        ),
        migrations.AddField(
            model_name='projects',
            name='project_paragraph',
            field=models.TextField(blank=True),
        ),
    ]
