# Generated by Django 2.2.7 on 2019-11-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_aboutpage_overviewimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_info_size',
            field=models.TextField(blank=True),
        ),
    ]
