# Generated by Django 2.2.7 on 2019-11-27 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0010_document_file_hash'),
        ('home', '0011_projects_project_info_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
    ]
