# Generated by Django 2.2.7 on 2019-11-28 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_projectpage_project_image_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectpage',
            old_name='project_image_2',
            new_name='project_image_bottom_section',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='project_document',
            new_name='project_brochure',
        ),
    ]
