# Generated by Django 2.2.7 on 2019-11-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20191128_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='project_pride',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='project_pride_paragraph',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_name',
            field=models.TextField(blank=True),
        ),
    ]
