# Generated by Django 2.2.7 on 2019-12-04 12:49

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0016_enquiryfield_enquiryformsetting_enquirypage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuturePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('project_welcome_title', models.TextField(default='Welcome to')),
                ('project_title', models.TextField(default='2020-2030')),
                ('project_description', models.TextField(default='')),
                ('css_strings', models.TextField(blank=True)),
                ('project_information_title', models.TextField(blank=True)),
                ('project_information', models.TextField(blank=True)),
                ('hero_intro', wagtail.core.fields.RichTextField(blank=True)),
                ('project_intro', models.TextField(blank=True)),
                ('project_body', wagtail.core.fields.RichTextField(blank=True)),
                ('project_pride', models.TextField(blank=True)),
                ('project_pride_paragraph', models.TextField(blank=True)),
                ('hero_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('project_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('project_image_bottom_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='projects',
            name='page',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_floor_plans', to='home.ProjectPage'),
        ),
        migrations.CreateModel(
            name='FuturePageDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('detail_name', models.TextField(default='P')),
                ('detail_info', models.TextField(blank=True)),
                ('page', modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='future_project_details', to='home.FuturePage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
