# Generated by Django 2.2.7 on 2019-12-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20191205_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='coming_soon_title',
            field=models.TextField(blank=True),
        ),
    ]
