# Generated by Django 2.2.7 on 2019-12-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20191205_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='futurepage',
            name='hero_intro',
        ),
        migrations.AddField(
            model_name='futurepage',
            name='hero_intro_one',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='futurepage',
            name='hero_intro_three',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='futurepage',
            name='hero_intro_two',
            field=models.TextField(blank=True),
        ),
    ]
