# Generated by Django 2.2.7 on 2019-12-09 15:05

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20191209_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futurepage',
            name='hero_intro_one',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='futurepage',
            name='hero_intro_three',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='futurepage',
            name='hero_intro_two',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
