# Generated by Django 2.2.7 on 2019-12-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20191209_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futurepage',
            name='hero_intro_one',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='futurepage',
            name='hero_intro_three',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='futurepage',
            name='hero_intro_two',
            field=models.TextField(blank=True),
        ),
    ]
