# Generated by Django 2.2.7 on 2019-12-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20191209_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='hero_intro',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_intro_one',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_intro_three',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_intro_two',
            field=models.TextField(blank=True),
        ),
    ]
