# Generated by Django 2.2.7 on 2019-12-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20191209_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='coming_soon',
            field=models.TextField(blank=True, default='Coming Soon'),
        ),
    ]
