# Generated by Django 2.2.7 on 2019-12-11 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0027_projectpage_project_image_small'),
    ]

    operations = [
        migrations.AddField(
            model_name='futurepage',
            name='project_image_small',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
